### ISSUE TITLE
Error building documentation. "AttributeError: module 'pyspod' has no attribute '__copyright__'"

### ISSUE THREAD

**Issue by jdmoorman** [mengaldo/PySPOD#4]
Running the following as explained in `README.md` results in an error.

```bash
$ git clone https://github.com/mengaldo/PySPOD
$ cd PySPOD
$ python setup.py install
$ cd docs
$ make html
```

The resulting error message output by `make html` follows.

```text
Running Sphinx v2.4.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/jdmoorman/opt/miniconda3/lib/python3.7/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/jdmoorman/opt/miniconda3/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/jdmoorman/Git/PySPOD/docs/source/conf.py", line 74, in <module>
    copyright = pyspod.__copyright__
AttributeError: module 'pyspod' has no attribute '__copyright__'

make: *** [html] Error 2
```

Looks like the issue is related to the variables (e.g. `copyright`) defined on lines 22-29 of `docs/conf.py` being overwritten on lines 72-75 and 85-87 by undefined metadata from the `pyspod` package (e.g. `pyspod.__copyright__`).

**Comment by jdmoorman** [comment]
[openjournals/joss-reviews#2862](https://github.com/openjournals/joss-reviews/issues/2862)

**Comment by mengaldo** [comment]
@jdmoorman  This should be now fixed, thank you.
